<template>
    <div class="aboutBody" style="display: flex;justify-content: center">
        <div class="tableList">
            <figure class="wp-block-table">
                <table>
                    <tbody>
                    <tr>
                        <td>编码</td>
                        <td>笔形</td>
                        <td>笔画结构</td>
                        <td>例字</td>
                    </tr>
                    <tr>
                        <td>a</td>
                        <td>一</td>
                        <td>横</td>
                        <td>一，七</td>
                    </tr>
                    <tr>
                        <td>b</td>
                        <td>𠃍</td>
                        <td>横竖</td>
                        <td>口，马，侯，互</td>
                    </tr>
                    <tr>
                        <td>c</td>
                        <td>㇅</td>
                        <td>横竖横乙形</td>
                        <td>凹，九，飞，风</td>
                    </tr>
                    <tr>
                        <td>d</td>
                        <td>㇎</td>
                        <td>横竖横竖</td>
                        <td>凸，〇</td>
                    </tr>
                    <tr>
                        <td>e</td>
                        <td>𠃌</td>
                        <td>横竖左勾</td>
                        <td>刀，永，也，即</td>
                    </tr>
                    <tr>
                        <td>f</td>
                        <td>㇊</td>
                        <td>横竖右勾</td>
                        <td>认，微，鸠</td>
                    </tr>
                    <tr>
                        <td>g</td>
                        <td>乛</td>
                        <td>横勾</td>
                        <td>买，宝，欠，皮（注一）</td>
                    </tr>
                    <tr>
                        <td>h</td>
                        <td>㇇</td>
                        <td>横撇</td>
                        <td>又，今，争，饥（注二）</td>
                    </tr>
                    <tr>
                        <td>i</td>
                        <td>㇋</td>
                        <td>横撇横撇</td>
                        <td>及，建</td>
                    </tr>
                    <tr>
                        <td>j</td>
                        <td>𠄎</td>
                        <td>横撇左弯勾</td>
                        <td>队，乃，扬（注三）</td>
                    </tr>
                    <tr>
                        <td>k</td>
                        <td>丨</td>
                        <td>竖</td>
                        <td>十，日，古（注四）</td>
                    </tr>
                    <tr>
                        <td>l</td>
                        <td>𠃊</td>
                        <td>竖横</td>
                        <td>山，母，发，彖（注五）</td>
                    </tr>
                    <tr>
                        <td>m</td>
                        <td>𠃑</td>
                        <td>竖横竖，撇横撇</td>
                        <td>鼎，与，专，（注六）</td>
                    </tr>
                    <tr>
                        <td>n</td>
                        <td>乚</td>
                        <td>竖横上钩</td>
                        <td>电，己，心</td>
                    </tr>
                    <tr>
                        <td>o</td>
                        <td>亅</td>
                        <td>竖左勾</td>
                        <td>打，了</td>
                    </tr>
                    <tr>
                        <td>p</td>
                        <td>𠄌</td>
                        <td>竖右勾，竖提</td>
                        <td>以，瓦，岭，龈</td>
                    </tr>
                    <tr>
                        <td>q</td>
                        <td>㇓</td>
                        <td>撇</td>
                        <td>禾，人，百，小（注七）</td>
                    </tr>
                    <tr>
                        <td>r</td>
                        <td>𠃋</td>
                        <td>横撇，撇提</td>
                        <td>厶，亥，东（注八）</td>
                    </tr>
                    <tr>
                        <td>s</td>
                        <td>𡿨</td>
                        <td>撇长点</td>
                        <td>女，巡</td>
                    </tr>
                    <tr>
                        <td>t</td>
                        <td>㇏</td>
                        <td>捺</td>
                        <td>八，大，</td>
                    </tr>
                    <tr>
                        <td>u</td>
                        <td>㇁</td>
                        <td>左弯勾</td>
                        <td>犹，豕</td>
                    </tr>
                    <tr>
                        <td>v</td>
                        <td>㇂</td>
                        <td>右弯勾</td>
                        <td>戈，民</td>
                    </tr>
                    <tr>
                        <td>w</td>
                        <td>㇀</td>
                        <td>提</td>
                        <td>江，地，轩，驰</td>
                    </tr>
                    <tr>
                        <td>x</td>
                        <td>㇃</td>
                        <td>提，捺</td>
                        <td>之，过</td>
                    </tr>
                    <tr>
                        <td>y</td>
                        <td>(左点)</td>
                        <td>左点</td>
                        <td>刃，写，忆</td>
                    </tr>
                    <tr>
                        <td>z</td>
                        <td>丶</td>
                        <td>右点</td>
                        <td>衣，达，举</td>
                    </tr>
                    </tbody>
                </table>
            </figure>
        </div>
    </div>
</template>

<script>
export default {
    name: "about"
}
</script>

<style scoped>

</style>